print("Numele prenumele:       Biliciuc Ana-Maria")
print("Data si locul nasterii: 28 decembrie 2004, orasul Balti")
print("Varsta:                 15 ani")
print("Domiciliul:             Alexandru cel Bun 4o, apartamentul 49, nr.de telefon 060467309")
print("Scoala si clasa:        Institutia Publica Liceul Teoretic Mihai Eminescu clasa a 10-a C ")
print("Studii:                 2011-2015 I.P.L.T.M.Eminescu etapa primara, 2015-2020 I.P.L.T.M.Eminescu etapa gimnaziala, 2016-2020 Scoala de arte plastice pentru copii  ")
print("Performante:            2019- Premiul special la concursul international STRUCTURE AND COLOUR")
print("Abilitati:              Limba franceza nivel B1, cunosc limba engleza, romana, rusa la nivel de a scrie, citi, intelege si comunica")
print("Obiective profesionale: I.P.L.T.Mihai Eminescu etapa liceu, profil real bilingv, stiinte despre lumea inconjuratoare")
print("Pasiuni:                arta, sport,")
print("Semnatura:              Ana Maria Biliciuc")
print("Data:                   12.09.2020")